version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - MONGO_URI=mongodb+srv://praveen453:igishoot453@cluster0.zfvud.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo
    restart: always

  frontend:
    build:
      context: ./break-reminder-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
