name: Backend CI/CD

on:
  push:
    branches:
      - main
      - staging
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Docker Image
        run: docker build -t praveen4531/break-reminder-backend .

      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker push praveen4531/break-reminder-backend

      - name: Deploy to AWS ECS
        run: |
          aws ecs update-service --cluster break-reminder-cluster --service break-reminder-backend-service --force-new-deployment
