name: Deploy Frontend
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy Frontend
        run: |
          # Example: Deploy to Netlify (replace with actual deployment command)
          curl -sL https://github.com/netlify/cli/releases/download/v3.0.0/netlify-cli-linux-x64.tar.gz | tar xz
          ./netlify deploy --prod --dir=build